### ISSUE TITLE
Feature Request: Order category by updated_date

### ISSUE THREAD

**Issue by Cherry** [BukGet/api#111]
Sorting a category by plugin updated date would be extremely useful such as the default sorting http://dev.bukkit.org/bukkit-plugins/?category=admin-tools. Sorting by slug is unreliable (slugs don't always match plugin names), and sorting by plugin name is just as unreliable with many names being blank. If this does already exist, and I've simply missed the documentation for such feature, please do let me know.

**Comment by SteveMcGrath** [comment]
This is an old post thats been open for some time, but in the interest of closing it out, it was always documented.

http://bukget.org/documentation#categories-category-plugin-listing

**Comment by Cherry** [comment]
Thanks Steve,

Unless I'm mistaken, the `updated_date`, or `date`(?) field is never appropriated, and therefore not available in the response. As far as I can tell, only the following fields are available for such a request: `'slug', 'server', 'description', 'authors', 'categories', 'versions', 'plugin_name'`, as dictated by https://github.com/BukGet/generator/blob/master/bukgen/bukkit.py#L288. 

Trying something like `https://api.bukget.org/3/categories/bukkit/Admin%20Tools?fields=slug,plugin_name,description,versions&sort=-versions.date`, which is the best I can come up with the documentation available, yields a `invalid category` error.

Am I missing the documentation for this, or is this simply not possible at this time?
