### ISSUE TITLE
Enable Gzip Compression

### ISSUE THREAD

**Issue by rylinaux** [BukGet/api#118]
Is there any reason gzip compression is not enabled on the web server that serves up the API responses? It could save some bandwidth and time in fetching the assets.

Is this isn't an issue, could the feature be enabled? 

![gzip](https://cloud.githubusercontent.com/assets/1282383/6992846/ce0b3ed4-dab6-11e4-9adb-eace55705842.PNG)

Regards,
Ryan

**Comment by DMarby** [comment]
Hello,

BukGet will now be serving gzipped content if the client sends a correct Accept-Encoding header.
