### ISSUE TITLE
False information in plugin details

### ISSUE THREAD

**Issue by aft2d** [BukGet/api#119]
If you request the details of of PlotMe you get false information.
https://api.bukget.org/3/plugins/bukkit/plotme/latest

You can see that the API returns information from DynmapPlotMe and from PlotMe.
Main, description, hard_dependencies, authors and some others are from DynmapPlotMe.
It looks like that some information gets mixed together.

`{
website: "http://dev.bukkit.org/bukkit-plugins/plotme",
dbo_page: "http://dev.bukkit.org/bukkit-plugins/plotme",
main: "com.worldcretornica.dynmapplotme.DynmapPlotMe",
description: "Link between dynmap and PlotMe",
curse_id: 40349,
versions: [
{
status: "Semi-normal",
commands: [ ],
game_versions: [
"1.8.1"
],
changelog: "PGRpdiBjbGFzcz0iY29udGVudC1ib3gtaW5uZXIiPgo8aDM+CiBDaGFuZ2UgbG9nCjwvaDM+Cjxw PgogRml4ZXMgYSBkYXRhYmFzZSBpc3N1ZSB3aXRoIFNRTGxpdGUKIDxiciAvPgogUGFydGlhbGx5 IGZpeGVzIHdvcmxkZWRpdCBhbnl3aGVyZS4gVGhpcyB3aWxsIGJlIHByb3Blcmx5IGZpeGVkIGlu IDAuMTcKIDxiciAvPgogVGhpcyByZWxlYXNlIGlzIGNvbXBhdGlibGUgd2l0aCBhbGwgMC4xNi5Y IGFkZG9ucwogPGJyIC8+CiBOaW5qYVVwZGF0ZQo8L3A+CjwvZGl2Pg== ",
dbo_version: "0.16.3",
hard_dependencies: [
"dynmap",
"PlotMe"
],
download: "http://dev.bukkit.org/media/files/860/66/PlotMe.zip",
version: "0.3",
link: "http://dev.bukkit.org/bukkit-plugins/plotme/files/42-0-16-3/",
file_id: 86066,
date: 1423382130,
permissions: [ ],
filename: "PlotMe.zip",
type: "Release",
slug: "42-0-16-3",
soft_dependencies: [ ],
md5: "4b855624773450ab1d1821c4b22314ca"
}
],
popularity: {
monthly: 863,
total: 43104,
daily: 18,
weekly: 176
},
plugin_name: "DynmapPlotMe",
server: "bukkit",
curse_link: "https://www.curse.com/bukkit-plugins/minecraft/plotme",
logo_full: "",
authors: [
"zachbora"
],
logo: "",
slug: "plotme",
categories: [
"Anti-Griefing Tools",
"Admin Tools",
"Teleportation",
"World Generators"
],
stage: "Release"
}`

**Comment by DMarby** [comment]
Closing this due to the project not being active anymore.
