### ISSUE TITLE
New update to Bukkit's site has broken plugin downloads.

### ISSUE THREAD

**Issue by SpiderRobotMan** [BukGet/api#120]
Most plugin downloads now lead to dead pages, 404'ing. For example Essentials: http://api.bukget.org/3/plugins/bukkit/essentials/latest/download

**Comment by matthiasnd** [comment]
Here's the update news: https://dev.bukkit.org/news/838-bukkitdev-gets-an-upgrade

They have changed the whole website to curseforge, which will maybe break the whole API.
It would be good to know, if there will be an update or if we have to find other solutions.

**Comment by DMarby** [comment]
Hi, due to these recent changes we've decided to shut down BukGet. Please see https://bukget.org/news/BukGet-Winding-Down/ for more information.
